### ISSUE TITLE
Permissions required to complete the HelloWorld guide not listed + process is too opaque

### ISSUE THREAD

**Issue by chriskiehl** [litlang/lit#10]
>Stratc will need to create resources on your AWS account and will need credentials to do that, so go ahead and set up your shared credentials file by following the instructions here. 

1\. Which perms are needed, fam? Lambda + Gateway? IAM involved? Full access to everything? 

Maybe give a link to a premade policy so we can (a) see the scope of the access you're requesting and (b) attach it to a limited scope user for testing out the HelloWorld?

2\. You should explain wtf it's gunna do on your behalf. It's a _super high_ trust barrier to overcome running someone else's code, that you just learned about, and that has just asked for your AWS account, and will do [???]. 

I mean, hell, _I_ trust you to not be malicious, but I still ran it first with a permission-less user to see what all it was gunna do. Which brings me to, 

3\. do you _need_ IAM role creation permissions in the HelloWorld? What do these roles you create _do_? Why are they there/needed? Are you haxxoring me?! 

4\. Probs needs a clean up / tear down option. _something_ happened in my AWS account, now I've gotta go track down what was modified so I can clean it up by hand.

**Comment by CaptainCharlieGreen** [comment]
Yea this is good feedback.

To answer your questions:
1)
Create Lambda
Create Role (with assume and invoke for lambda/APIGateway)
Create APIGateway
Upload S3 file

2)
Its gonna create shit

3)
Unfortunately yes because of APIGateway--it needs a role to assume to invoke whatever lambda HW runs on

4)
This is a great idea.  I've avoided it as non-mvp but it might be mvp.  Beyond making Strat feel safer and cleaner, users will eventually run into AWS limits like the 1000 Lambda function limit per account.

---
But let me ask you this: why do you care if there are a bunch of IAM roles in your account?  They're just records in a database somewhere.  The endgame with Strat is you never log into the AWS console at all.

That said, we're a long way off from the "endgame" and I think these additions are valuable to make people more comfortable with the tool.  Or maybe we go full Heroku and manage the AWS account for you...


And a further note on 1 and 2: this will probably expand and change in the future.

**Comment by CaptainCharlieGreen** [comment]
https://strat.world/User%20Guide/AWS

Linked to in the index.md file
