### ISSUE TITLE
Feature request: namespace generated role names 

### ISSUE THREAD

**Issue by chriskiehl** [litlang/lit#12]
Have generated infrastructure names be namespaced ala `::strat/151fb0259-blahblahblha`

Specifically, to make them sort together in the sea of IAM roles and enable easier searching

**Comment by CaptainCharlieGreen** [comment]
Looks like a good first commit : )

https://github.com/stratworld/strat/blob/master/svs/aws/awsResources/aws.js#L41
https://github.com/stratworld/strat/blob/master/svs/aws/awsResources/aws.js#L28
https://github.com/stratworld/strat/blob/master/svs/aws/awsResources/iam/iam.js#L91

Getting the service name in there would be harder but a good value too

**Comment by CaptainCharlieGreen** [comment]
Or maybe here for IAM
https://github.com/stratworld/strat/blob/master/svs/aws/awsResources/iam/iam.js#L106

Probably need to change this too:

https://github.com/stratworld/strat/blob/master/svs/aws/awsResources/iam/iam.js#L167

Unfortunately the IAM creation stuff is a bit new and messy.  The whole AWS SVS needs to be refactored since it was originally built to be generic and cloud agnostic.
